### PR TITLE
experiment: support Python 3.7

### PR DESCRIPTION
**Pull request by paulswartz**

### CODE REVIEW

**Comment by araichev** [comment]
@paulswartz i'd accept this once Travis does.

**Comment by paulswartz** [comment]
Unfortunately, it looks like there are some issues with Travis and Python 3.7 at the moment: https://github.com/travis-ci/travis-ci/issues/9815

It also depends on a not-yet-released version of `pyproj`: might be better to hold off for now.

**Comment by araichev** [comment]
OK.

**Comment by araichev** [comment]
Done!

**Pull request closed without merging**
