### PR TITLE
validation updates for pathways

### PR DESCRIPTION
**Pull request by paulswartz**
- location types 3 and 4 are valid
- they do not require a lat/lon
- they do require a parent_station

The spec is available at https://bit.ly/gtfs-pathways

### CODE REVIEW

**Comment by araichev** [comment]
Hi @paulswartz, thanks for your contribution.
The GTFS-Pathways extension doesn't seem to be part of the official GTFS yet, as described at [gtfs.org](https://gtfs.org/) and at [Google](https://developers.google.com/transit/gtfs/reference/).  
At this point, i just want GTFSTK to support the official GTFS, which is work enough.
So i think i'll decline this merge request.

**Comment by paulswartz** [comment]
That's fair, though there is an open PR to make it part of the spec: https://github.com/google/transit/pull/143

**Comment by araichev** [comment]
OK, let's return to this issue when the dust settles and the official spec gets updated.  Feel free to poke me again when the time comes. Closing the issue for now.

**Comment by paulswartz** [comment]
@araichev hi there! The updates to the pathways spec have landed. Can we take another look at including these validation updates?

**Comment by araichev** [comment]
Hey @paulswartz , i don't see the pathways spec in the [Google docs](https://developers.google.com/transit/gtfs/reference/) but i do see it at [gtfs.org](https://gtfs.org), so i'm happy to receive merge requests to extend the GTFSTK validators to the new spec.
Got one for me?

**Comment by araichev** [comment]
Oh yeah, you do have a merge request for me, @paulswartz: this one.
You still happy with it, or do you want to amend it?

**Comment by paulswartz** [comment]
This is good for us: we haven't had any other validation failures.

**Comment by araichev** [comment]
Merged.
Thanks @paulswartz .

Say, if you have the time, could you comment on [Issue 12] (https://github.com/mrcagney/gtfstk/issues/12) about how you use GTFSTK?
I'm curious.

**Pull request merged**
